"""Add customer_comments field to quotations

Revision ID: c5b4823dc4e3
Revises: fbde8b5cf973
Create Date: 2025-12-01 18:18:14.244689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b4823dc4e3'
down_revision = 'fbde8b5cf973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('customer_comments')

    # ### end Alembic commands ###
